---
language: node_js
node_js:
  - "12.13.0"
before_script:
  - npm install
script:
  - npm run prettier:check
  - npm run lint
  - REACT_APP_API_KEY=fakekey npm run build
  - npm run coverage
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
