update_configs:
  -
    directory: /
    ignored_updates:
      -
        match:
          dependency_name: react-shadow
          version_requirement: 16.3.2
    package_manager: javascript
    update_schedule: daily
version: 1
