name: Stage deploy

on:
  push:
      branches-ignore:
        - 'master'

env:
  PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
  PR_SLUG: $(GITHUB_REF_NAME)
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-2

jobs:
  install:
    runs-on: ubuntu-latest
    name: Install and test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm install
      - run: npm test

  build:
    needs: install
    runs-on: ubuntu-latest
    environment: stage_deploy

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
      - uses: actions/setup-node@v2
      - run: npm install

      - name: Make
        run: make stage_build

      - name: Make
        run: make stage_sync_to_s3
